import { shadesOfPurple } from "@clerk/themes";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cravio - cuisine platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{baseTheme : shadesOfPurple}}>
      <html
        lang="en"
        suppressHydrationWarning
        className="h-full antialiased"
        >
    
        <body className={inter.className}>
          <Header />
          <main className="min-h-screen">{children}</main>

          <footer className="py-8 px-4 border-t">
            <div className="max-w-6xl mx-auto flex justify-center items-center">
              <p className="text-stone-500 text-sm">
                Made with ❤️ by sherinnnn
              </p>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}